const nodemailer = require("nodemailer");
const { logWithTime } = require("@utils/time-stamps.util");

/**
 * 📧 Core Mail Service
 * Responsibility: Just send the HTML provided. No logic.
 */

const createTransporter = () => {
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST || "smtp.gmail.com",
    port: parseInt(process.env.SMTP_PORT) || 587,
    secure: process.env.SMTP_SECURE === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASSWORD,
    },
  });
};

// Singleton Transporter (Baar baar create karne se connection pool bachta hai)
const transporter = createTransporter();

/**
 * 🚀 Fire-and-Forget Email Sender
 * @param {string} to - Recipient email
 * @param {string} subject - Email Subject
 * @param {string} htmlContent - Final HTML String (Generated by Utils)
 */
const sendEmail = async (to, subject, htmlContent) => {
  if (!to) {
    logWithTime(`⚠️ Email skipped: No recipient.`);
    return;
  }

  const emailConfig = {
    from: process.env.EMAIL_FROM || `"${process.env.APP_NAME || 'Admin'}" <${process.env.SMTP_USER}>`,
    to: to,
    subject: subject,
    html: htmlContent,
  };

  // ❌ NO AWAIT here for Fire-and-Forget
  // Callback handle karega success/error background mein
  transporter.sendMail(emailConfig, (error, info) => {
    if (error) {
      logWithTime(`❌ [Background] Email failed to ${to}: ${error.message}`);
    } else {
      logWithTime(`✅ [Background] Email sent to ${to}: ${info.messageId}`);
    }
  });
};

module.exports = { sendEmail };