const AUTH_LOG_EVENTS = Object.freeze({
  LOGIN: "LOGIN",
  LOGOUT_ALL_DEVICE: "LOGOUT_ALL_DEVICE",
  ACTIVATE: "ACTIVATE",
  DEACTIVATE: "DEACTIVATE",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  REGISTER: "REGISTER",
  LOGOUT_SPECIFIC_DEVICE: "LOGOUT_SPECIFIC_DEVICE",
  UPDATE_ACCOUNT_DETAILS: "UPDATE_ACCOUNT_DETAILS",
  ENABLE_2FA: "ENABLE_2FA",
  DISABLE_2FA: "DISABLE_2FA",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  VERIFY_DEVICE: "VERIFY_DEVICE",
  VERIFY_PHONE: "VERIFY_PHONE",
  RESEND_VERIFICATION_LINK: "RESEND_VERIFICATION_LINK",
  RESEND_VERIFICATION_OTP: "RESEND_VERIFICATION_OTP",
  DEVICE_CREATE: "DEVICE_CREATE",
  DEVICE_UPDATE: "DEVICE_UPDATE",
  USER_DEVICE_CREATE: "USER_DEVICE_CREATE",
  USER_DEVICE_UPDATE: "USER_DEVICE_UPDATE"
});

module.exports = {
  AUTH_LOG_EVENTS
}
