const AUTH_LOG_EVENTS = Object.freeze({
  LOGIN: "LOGIN",
  LOGOUT_ALL_DEVICE: "LOGOUT_ALL_DEVICE",
  ACTIVATE: "ACTIVATE",
  DEACTIVATE: "DEACTIVATE",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  REGISTER: "REGISTER",
  LOGOUT_SPECIFIC_DEVICE: "LOGOUT_SPECIFIC_DEVICE",
  UPDATE_ACCOUNT_DETAILS: "UPDATE_ACCOUNT_DETAILS"
});

module.exports = {
  AUTH_LOG_EVENTS
}
