const AUTH_LOG_EVENTS = Object.freeze({
  LOGIN: "LOGIN",
  LOGOUT_ALL_DEVICE: "LOGOUT_ALL_DEVICE",
  ACTIVATE: "ACTIVATE",
  DEACTIVATE: "DEACTIVATE",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  REGISTER: "REGISTER",
  LOGOUT_SPECIFIC_DEVICE: "LOGOUT_SPECIFIC_DEVICE",
  UPDATE_ACCOUNT_DETAILS: "UPDATE_ACCOUNT_DETAILS",
  ENABLE_2FA: "ENABLE_2FA",
  DISABLE_2FA: "DISABLE_2FA",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  VERIFY_DEVICE: "VERIFY_DEVICE",
  VERIFY_PHONE: "VERIFY_PHONE",
  SEND_EMAIL_VERIFICATION: "SEND_EMAIL_VERIFICATION",
  SEND_PHONE_VERIFICATION: "SEND_PHONE_VERIFICATION",
  SEND_DEVICE_VERIFICATION: "SEND_DEVICE_VERIFICATION",
  SEND_FORGOT_PASSWORD_VERIFICATION: "SEND_FORGOT_PASSWORD_VERIFICATION",
  DEVICE_CREATE: "DEVICE_CREATE",
  DEVICE_UPDATE: "DEVICE_UPDATE",
  USER_DEVICE_CREATE: "USER_DEVICE_CREATE",
  USER_DEVICE_UPDATE: "USER_DEVICE_UPDATE"
});

// Events safe to show in end-user activity timeline.
const USER_VISIBLE_AUTH_LOG_EVENTS = Object.freeze([
  AUTH_LOG_EVENTS.LOGIN,
  AUTH_LOG_EVENTS.LOGOUT_ALL_DEVICE,
  AUTH_LOG_EVENTS.LOGOUT_SPECIFIC_DEVICE,
  AUTH_LOG_EVENTS.REGISTER,
  AUTH_LOG_EVENTS.VERIFY_EMAIL,
  AUTH_LOG_EVENTS.VERIFY_PHONE,
  AUTH_LOG_EVENTS.VERIFY_DEVICE,
  AUTH_LOG_EVENTS.FORGOT_PASSWORD,
  AUTH_LOG_EVENTS.RESET_PASSWORD,
  AUTH_LOG_EVENTS.CHANGE_PASSWORD,
  AUTH_LOG_EVENTS.ENABLE_2FA,
  AUTH_LOG_EVENTS.DISABLE_2FA,
  AUTH_LOG_EVENTS.UPDATE_ACCOUNT_DETAILS,
  AUTH_LOG_EVENTS.ACTIVATE,
  AUTH_LOG_EVENTS.DEACTIVATE,
  AUTH_LOG_EVENTS.DELETE_ACCOUNT
]);

module.exports = {
  AUTH_LOG_EVENTS,
  USER_VISIBLE_AUTH_LOG_EVENTS
}