const SYSTEM_LOG_EVENTS = {
    CRON_EXECUTION: "CRON_EXECUTION",
    INTERNAL_API_CALL: "INTERNAL_API_CALL",
    BOOTSTRAP_ADMIN: "BOOTSTRAP_ADMIN"
};

const STATUS_TYPES = {
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE",
    PENDING: "PENDING"
};

const SERVICE_NAMES = {
    AUTH_SERVICE: "AUTH_SERVICE",
    ADMIN_PANEL_SERVICE: "ADMIN_PANEL_SERVICE",
};

module.exports = {
    SYSTEM_LOG_EVENTS,
    STATUS_TYPES,
    SERVICE_NAMES
};