module.exports = Object.freeze([
  "LOGIN",
  "LOGOUT_ALL_DEVICE",
  "ACTIVATE",
  "DEACTIVATE",
  "BLOCKED",
  "UNBLOCKED",
  "CHANGED_PASSWORD",
  "REGISTER",
  "LOGOUT_SPECIFIC_DEVICE",
  "CHECK_AUTH_LOGS",
  "GET_ACTIVE_DEVICES_LOG",
  "ACCESS_TOKEN",
  "REFRESH_TOKEN",
  "UPDATE_ACCOUNT_DETAILS",
  "PROVIDE_ACCOUNT_DETAILS"
]);
